[profile.default]
src = "src"
out = "out"
libs = ["lib"]
ffi = false

remappings = [
"ds-test/=lib/forge-std/lib/ds-test/src/",
"forge-std/=lib/forge-std/src/",
"@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
"@chainlink-ccip/contracts/src/=lib/chainlink/contracts/src/",
"@chainlink/local/=lib/chainlink-local/",
"@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
"@solmate/=lib/solmate/src/"
]

#Force foundry to use the remappings in the foundry.toml file or remappings.txt
auto_detect_remappings = false

# Filepath permissions
# The modified foundry.toml gives fs_premission the access to read the whole project directory hence you can read any file or line using vm.readFile() or vm.readLine() cheatcode in foundry
fs_permissions = [
    { access = "read", path = "./"},
]


# Set invariant testing options - depth is the number of calls in a single run
# Fail on revert can make it super easy to get up and running, however, there is risk of just going test to test and reverting -
#-everytime and not diving deeper because the calls we are making don't make sense. 
# An example might be passing random address inputs to a function that don't make sense and therefore we don't actually get into the fucntion itself
[invariant]
runs = 128
depth = 50
fail_on_revert = true

# RPC URL aliases - alias on left, value on right
# Can also refer to environment variables
# example:
# zksync = "https://mainnet.era.zksync.io"
# EXAMPLES ONLY - UPDATE WITH PROJECT
[rpc_endpoints]
optimism = "https://optimism.alchemyapi.io/v2/..."
mainnet = "${RPC_MAINNET}" 

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
extra_output = ["storageLayout", "metadata"]


[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[etherscan]
# zksync = no keey needed for zksync
arbitrum = { key = "${API_KEY_ARBISCAN}" }
avalanche = { key = "${API_KEY_SNOWTRACE}" }
bnb_smart_chain = { key = "${API_KEY_BSCSCAN}" }
gnosis_chain = { key = "${API_KEY_GNOSISSCAN}" }
goerli = { key = "${API_KEY_ETHERSCAN}" }
mainnet = { key = "${API_KEY_ETHERSCAN}" }
optimism = { key = "${API_KEY_OPTIMISTIC_ETHERSCAN}" }
polygon = { key = "${API_KEY_POLYGONSCAN}" }
sepolia = { key = "${API_KEY_ETHERSCAN}" }


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
